config/routes.rb
Rails.application.routes.draw do
  resources :artists do
    resources :songs, only: [:index, :new, :create, :destroy], module: :artists
  end

  resources :songs, only: [:index, :show, :edit, :update, :destroy]

  resources :playlists, only: [:index, :new, :create, :show, :edit, :update]

  get '/auth/spotify/callback', to: 'sessions#create'
  delete '/logout', to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  validates :name, presence: true

  has_many :playlist_songs
  has_many :songs, through: :playlist_songs

  def selected?(song)
    songs.include?(song)
  end
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ApplicationRecord
  validates :title, presence: true

  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_auth(auth)
    User.find_or_create_by(
      uid: auth["info"]["id"],
      provider: auth["provider"],
      name: auth["info"]["display_name"] || auth["info"]["id"]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/artists/songs_controller.rb
class Artists::SongsController < ApplicationController
  before_action :set_artist, only: [:new, :create, :index, :destroy]
  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.create(song_params)
    if @song.save
      redirect_to @song
    else
      render :new
    end
  end

  def index
    @songs = @artist.songs.order(:title)
  end

  def destroy
    @artist.songs.find(params[:id]).destroy
    redirect_to artist_songs_path
  end

  private

   def song_params
     params.require(:song).permit(:title)
   end

   def set_artist
     @artist = Artist.find(params[:artist_id])
   end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def show
  end

  def create
    @artist = Artist.create(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

   def set_artist
     @artist = Artist.find(params[:id])
   end

   def artist_params
     params.require(:artist).permit(:name,:image_path)
   end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update]
  before_action :set_songs, only: [:new, :edit]
  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.create(playlist_params)
    if @playlist.save
      redirect_to @playlist
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist
    else
      render :edit
    end
  end

  private

   def playlist_params
     params.require(:playlist).permit(:name, song_ids:[])
   end

   def set_playlist
     @playlist = Playlist.find(params[:id])
   end

   def set_songs
     @songs = Song.all
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to playlists_path
    end
  end

  def destroy
    session.clear
    redirect_to playlists_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  def index
    @songs = Song.all.order(:title)
  end

  def show
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  private

   def song_params
     params.require(:song).permit(:title)
   end

   def set_song
     @song = Song.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.haml
= form_for @artist do |f|
  = render partial: "shared/errors", locals: { target: @artist }

  %p
    = f.label :name
    = f.text_field :name
  %p
    = f.label :image_path
    = f.text_field :image_path
  %p= f.submit

app/views/artists/edit.html.haml
%h1= "Edit #{@artist.name}"

= render partial: "form"

app/views/artists/index.html.haml
= link_to "New artist", new_artist_path
%ul
- @artists.each do |artist|
  %li= link_to artist.name, artist

app/views/artists/new.html.haml
%h1= "Create new artist"

= render partial: "form"

app/views/artists/show.html.haml
%h1= @artist.name

=image_tag(@artist.image_path)

%p
  = link_to "View All Songs", artist_songs_path(@artist)
%p
  = link_to "New song", new_artist_song_path(@artist)
%p
  = link_to "Edit artist", edit_artist_path(@artist)
%p
  = link_to "Delete artist", artist_path(@artist), method: :delete
%p
  = link_to "All Artists", artists_path

app/views/artists/songs/index.html.haml
%h1
  = "All Songs for "
  = link_to @artist.name, @artist

%ul
  - @songs.each do |song|
    %li
      = link_to song.title, song
      = " ("
      = link_to "Delete #{song.title}", artist_song_path(@artist, song), method: :delete
      = ") "

app/views/artists/songs/new.html.haml
%h1= "New Song"
%p= "Add a new song for #{@artist.name}"

= render partial: "songs/form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MixMaster
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    - if current_user
      %h3= "Welcome, #{current_user.name}"
      %p= link_to "Sign out", logout_path, method: :delete
    - else
      %p= link_to "Sign in with Spotify", "/auth/spotify"
    = yield

app/views/playlists/_form.html.haml
= form_for @playlist do |f|
  = render partial: "shared/errors", locals: { target: @playlist }

  %p
    = f.label :name
    = f.text_field :name
  %ul
    - @songs.each do |song|
      %li
        = check_box_tag(:song_ids, song.id, @playlist.selected?(song), :name=> 'playlist[song_ids][]', id: "song-#{song.id}")
        = song.title
  %p
    = f.submit

app/views/playlists/edit.html.haml
%h1= "Edit #{@playlist.name}"

= render partial: "form"

app/views/playlists/index.html.haml
%h1= "Playlists"

%ul
  - @playlists.each do |playlist|
    %li= link_to playlist.name, playlist

%p
  = link_to "New playlist", new_playlist_path

app/views/playlists/new.html.haml
%h1= "New Playlist"

= render partial: "form"

app/views/playlists/show.html.haml
%h1= @playlist.name

%p= link_to "Edit", edit_playlist_path(@playlist)

- if ! @playlist.songs.empty?
  %ul
    - @playlist.songs.each do |song|
      %li= link_to song.title, song

app/views/shared/_errors.html.haml
- if target.errors.any?
  %h2= "#{pluralize(target.errors.count, "error")} + prohibited this record from being saved:"
  %ul
    - target.errors.full_messages.each do |error|
      %li= error

app/views/songs/_form.html.haml
= form_for [@artist, @song] do |f|
  = render partial: "shared/errors", locals: { target: @song }

  %p
    = f.label :title
    = f.text_field :title
  %p= f.submit

app/views/songs/edit.html.haml
%h1= "Edit #{@song.title}"

= render partial: "form"

app/views/songs/index.html.haml
%h1= "All Songs"

%ul
  - @songs.each do |song|
    %li
      = link_to song.title, song
      = " ("
      = link_to "Delete #{song.title}", song, method: :delete
      = ") "

app/views/songs/new.html.haml
%h1= "New Song"
%p= "Add a new song for #{@artist.name}"

= render partial: "form"

app/views/songs/show.html.haml
%h1= @song.title

%h2= link_to @song.artist.name, artist_path(@song.artist)

%p= link_to "Edit song", edit_song_path(@song)